# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cet4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eword', models.CharField(max_length=128)),
                ('cword', models.CharField(max_length=128)),
                ('sentence', models.CharField(max_length=128)),
                ('classs', models.CharField(default='cet4', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='cet6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eword', models.CharField(max_length=128)),
                ('cword', models.CharField(max_length=128)),
                ('sentence', models.CharField(max_length=128)),
                ('classs', models.CharField(default='cet6', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='tofu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eword', models.CharField(max_length=128)),
                ('cword', models.CharField(max_length=128)),
                ('sentence', models.CharField(max_length=128)),
                ('classs', models.CharField(default='tofu', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='yasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eword', models.CharField(max_length=128)),
                ('cword', models.CharField(max_length=128)),
                ('sentence', models.CharField(max_length=128)),
                ('classs', models.CharField(default='yasi', max_length=128)),
            ],
        ),
    ]
