# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20160612_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='cet4word',
            name='kword',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cet6word',
            name='kword',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tofuword',
            name='kword',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yasiword',
            name='kword',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
