# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20160612_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eword', models.CharField(max_length=128)),
                ('cword', models.CharField(max_length=128)),
                ('kword', models.CharField(max_length=128)),
                ('sentence', models.CharField(max_length=128)),
                ('classs', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='cet4word',
        ),
        migrations.DeleteModel(
            name='cet6word',
        ),
        migrations.DeleteModel(
            name='tofuword',
        ),
        migrations.DeleteModel(
            name='yasiword',
        ),
    ]
