# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20160612_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
